packages:
  - "backend"
  - "frontend"
  - "shared"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  onnxruntime-node: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
